steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_IMAGE}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,DB_USER=${_DB_USER},STRIPE_WEBHOOK_SECRET=${_STRIPE_WEBHOOK_SECRET},_STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY},NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY},OAUTH_REDIRECT_URI=${_OAUTH_REDIRECT_URI},OAUTH_ISSUER=${_OAUTH_ISSUER},OAUTH_CLIENT_SECRET=${_OAUTH_CLIENT_SECRET},OAUTH_CLIENT_ID=${_OAUTH_CLIENT_ID},DB_PORT=${_DB_PORT},DB_PASSWORD=${_DB_PASSWORD},DB_NAME=${_DB_NAME},DB_HOST=${_DB_HOST},JWT_SECRET=${_JWT_SECRET},NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},NEXTAUTH_URL=${_NEXTAUTH_URL}'
    
substitutions:
  _IMAGE: 'us-central1-docker.pkg.dev/crypto-arcade-401717/paiecashplay/fundation:latest'
  _SERVICE: 'paiecashplay-service'
  _REGION: 'us-central1'
  _DB_HOST: 'db.paiecashplay.com'
  _DB_USER: 'donation'
  _DB_PORT: '3306'
  _DB_PASSWORD: 'donation12344321'
  _DB_NAME: 'bd-donation'
  _JWT_SECRET: 'your-super-secret-jwt-key-production'
  _NEXTAUTH_SECRET: 'your-nextauth-secret-production'
  _NEXTAUTH_URL: 'https://fundation.paiecashplay.com'
  _OAUTH_CLIENT_ID: 'client_1754945913182_044b980g9'
  _OAUTH_CLIENT_SECRET: '2074687b6fdb69ba0dfd1da2837b192697c54b8fd7c439331838c074a6eda4bb'
  _OAUTH_ISSUER: 'https://auth.paiecashplay.com'
  _OAUTH_REDIRECT_URI: 'https://fundation.paiecashplay.com/api/auth/callback'
  _NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'pk_live_51RVbQ3GKyMLrJHF3kBfoDA4R2YdZWmPVyPeph0i2agiMzv3HNXkeSTvZcMXpwKRxlnkb1BHEpdpcJNDWCDmgSfbt00wRjJDF0Y'
  _STRIPE_SECRET_KEY: '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'
  _STRIPE_WEBHOOK_SECRET: 'whsec_SIZt5ijN4qQcEgSlkJQ6noSsaDjpVWPh'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: paicasplay-build-run@crypto-arcade-401717.iam.gserviceaccount.com

# Timeout de 10 minutes
timeout: 600s
