steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - '${_IMAGE}'
    - '--build-arg'
    - 'DB_HOST=${_DB_HOST}'
    - '--build-arg'
    - 'DB_USER=${_DB_USER}'
    - '--build-arg'
    - 'DB_PORT=${_DB_PORT}'
    - '--build-arg'
    - 'DB_PASSWORD=${_DB_PASSWORD}'
    - '--build-arg'
    - 'DB_NAME=${_DB_NAME}'
    - '--build-arg'
    - 'STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY}'
    - '--build-arg'
    - 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}'
    - '--build-arg'
    - 'JWT_SECRET=${_JWT_SECRET}'
    - '--build-arg'
    - 'NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
    - '--build-arg'
    - 'NEXTAUTH_URL=${_NEXTAUTH_URL}'
    - '--build-arg'
    - 'OAUTH_CLIENT_ID=${_OAUTH_CLIENT_ID}'
    - '--build-arg'
    - 'OAUTH_CLIENT_SECRET=${_OAUTH_CLIENT_SECRET}'
    - '--build-arg'
    - 'NEXT_PUBLIC_OAUTH_ISSUER=${_NEXT_PUBLIC_OAUTH_ISSUER}'
    - '--build-arg'
    - 'NEXT_PUBLIC_OAUTH_REDIRECT_URI=${_NEXT_PUBLIC_OAUTH_REDIRECT_URI}'
    - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_IMAGE}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - |
        DB_HOST=${_DB_HOST},
        DB_USER=${_DB_USER},
        DB_PORT=${_DB_PORT},
        DB_PASSWORD=${_DB_PASSWORD},
        DB_NAME=${_DB_NAME},
        DATABASE_URL=${_DATABASE_URL},
        JWT_SECRET=${_JWT_SECRET},
        NEXTAUTH_SECRET=${_NEXTAUTH_SECRET},
        NEXTAUTH_URL=${_NEXTAUTH_URL},
        OAUTH_CLIENT_ID=${_OAUTH_CLIENT_ID},
        OAUTH_CLIENT_SECRET=${_OAUTH_CLIENT_SECRET},
        NEXT_PUBLIC_OAUTH_ISSUER=${_NEXT_PUBLIC_OAUTH_ISSUER},
        NEXT_PUBLIC_OAUTH_REDIRECT_URI=${_NEXT_PUBLIC_OAUTH_REDIRECT_URI},
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY},
        STRIPE_SECRET_KEY=${_STRIPE_SECRET_KEY},
        STRIPE_WEBHOOK_SECRET=${_STRIPE_WEBHOOK_SECRET}
     

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: paicasplay-build-run@crypto-arcade-401717.iam.gserviceaccount.com

# Timeout de 10 minutes
timeout: 600s
