FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./
RUN npm ci --only=production

# Copier le code source
COPY . .

# Variables d'environnement par défaut (à surcharger en production)
ENV NODE_ENV=production

# Arguments de build pour les variables de base de données
ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_USER
ENV DB_USER=$DB_USER

ARG DB_PORT
ENV DB_PORT=$DB_PORT

ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD

ARG DB_NAME
ENV DB_NAME=$DB_NAME

ARG STRIPE_SECRET_KEY
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY

ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY

ARG STRIPE_WEBHOOK_SECRET
ENV STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET

ARG JWT_SECRET
ENV JWT_SECRET=$JWT_SECRET

ARG NEXTAUTH_SECRET
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET

ARG NEXTAUTH_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL

ARG OAUTH_CLIENT_ID
ENV OAUTH_CLIENT_ID=$OAUTH_CLIENT_ID

ARG OAUTH_CLIENT_SECRET
ENV OAUTH_CLIENT_SECRET=$OAUTH_CLIENT_SECRET

ARG OAUTH_ISSUER
ENV OAUTH_ISSUER=$OAUTH_ISSUER

ARG OAUTH_REDIRECT_URI
ENV OAUTH_REDIRECT_URI=$OAUTH_REDIRECT_URI


# Rendre le script start.sh exécutable
RUN chmod +x start.sh

# Build de l'application
RUN npm run build

EXPOSE 8080

CMD ["./start.sh"]